import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function TermsOfService() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Button variant="ghost" onClick={() => navigate(-1)} className="mb-6 gap-2"><ArrowLeft className="h-4 w-4" /> Back</Button>
        <h1 className="text-3xl font-bold font-display mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: April 9, 2026</p>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-muted-foreground [&_h2]:text-foreground [&_h2]:font-display [&_h2]:text-xl [&_h2]:mt-8 [&_h2]:mb-3 [&_strong]:text-foreground">
          <p>Welcome to Voishper ("we," "our," or "us"). By accessing or using our platform at voishper.lovable.app (the "Service"), you agree to be bound by these Terms of Service ("Terms"). Please read them carefully before using our Service.</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By creating an account, accessing, or using any part of the Service, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree, you must discontinue use of the Service immediately. We reserve the right to modify these Terms at any time, and your continued use constitutes acceptance of any changes.</p>

          <h2>2. Description of Service</h2>
          <p>Voishper is an AI-powered customer support platform that enables businesses to create intelligent chatbots trained on their own data. The Service includes website scraping tools for knowledge base creation, an embeddable chat widget, lead capture functionality, real-time analytics, and administrative controls. The AI responses are generated using large language models and are based on the knowledge base content provided by the user.</p>

          <h2>3. User Accounts & Eligibility</h2>
          <p>You must be at least 18 years of age or the age of majority in your jurisdiction to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate. We reserve the right to suspend or terminate accounts that violate these Terms or that we reasonably believe are being used for fraudulent or malicious purposes.</p>

          <h2>4. Subscription Plans & Payment</h2>
          <p>The Service offers a Free Plan with limited features (1 website scrape, 50 AI messages per month) and a Premium Plan with expanded capabilities. Premium subscriptions are billed on a monthly basis. All payments are processed through our manual payment verification system. Refund requests are handled on a case-by-case basis. We reserve the right to change pricing with 30 days' prior notice. Failure to maintain an active subscription will result in the account reverting to Free Plan limitations.</p>

          <h2>5. Acceptable Use Policy</h2>
          <p>You agree not to use the Service to: (a) violate any applicable laws or regulations; (b) infringe upon intellectual property rights of any third party; (c) distribute malware, spam, or harmful content; (d) attempt to gain unauthorized access to other users' data or our infrastructure; (e) scrape or harvest data from websites without proper authorization from the website owner; (f) create chatbots that provide misleading, fraudulent, or harmful information; (g) use the AI to generate content that is discriminatory, harassing, or threatening; or (h) resell or redistribute the Service without our written consent. Violations may result in immediate account suspension or termination.</p>

          <h2>6. Intellectual Property</h2>
          <p>All rights, title, and interest in the Service, including its technology, branding, design, and documentation, remain the exclusive property of Voishper. You retain ownership of the content you upload to the platform. By uploading content, you grant us a limited, non-exclusive license to process, store, and use that content solely for the purpose of providing the Service. You represent and warrant that you have the necessary rights and permissions to upload and use any content you provide.</p>

          <h2>7. AI-Generated Content Disclaimer</h2>
          <p>The AI responses generated by your chatbots are based on the knowledge base content you provide. While we strive for accuracy, AI-generated content may occasionally contain errors, omissions, or inaccuracies. <strong>You are solely responsible for reviewing and validating the accuracy of AI responses before relying on them for critical business decisions.</strong> Voishper makes no warranties regarding the accuracy, completeness, or fitness for a particular purpose of any AI-generated content.</p>

          <h2>8. Data Scraping Responsibilities</h2>
          <p>When using our website scraping feature, you are solely responsible for ensuring that you have the legal right and proper authorization to scrape and use content from any website you target. You agree to comply with all applicable laws, including but not limited to copyright laws, the Computer Fraud and Abuse Act, and the website's own terms of service and robots.txt directives. Voishper is not responsible for any legal consequences arising from your unauthorized scraping of third-party websites.</p>

          <h2>9. Service Availability & Limitation of Liability</h2>
          <p>We aim to provide reliable and uninterrupted access to the Service but do not guarantee 100% uptime. The Service is provided "as is" and "as available" without warranties of any kind, express or implied. To the maximum extent permitted by law, Voishper shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.</p>

          <h2>10. Account Termination</h2>
          <p>We may suspend or terminate your account at our sole discretion if we believe you have violated these Terms, engaged in fraudulent activity, or posed a security risk to our platform or other users. Upon termination, your right to use the Service ceases immediately. We may retain your data for a reasonable period in accordance with our data retention policies and applicable legal requirements. You may request account deletion by contacting our support team.</p>

          <h2>11. Governing Law & Dispute Resolution</h2>
          <p>These Terms shall be governed by and construed in accordance with applicable international commercial law principles. Any disputes arising from these Terms or your use of the Service shall first be attempted to be resolved through good-faith negotiation. If negotiation fails, disputes shall be submitted to binding arbitration in accordance with internationally recognized arbitration rules.</p>

          <h2>12. Contact Information</h2>
          <p>For questions or concerns regarding these Terms, please contact us at <strong>support@voishper.lovable.app</strong> or through the Voishper platform's built-in support widget.</p>
        </div>
      </div>
    </div>
  );
}
